apiVersion: v1
data:
  PORT: '4000'
  TYPEORM_HOST: loadbalancer
  TYPEORM_LOGGING: 'false'
  TYPEORM_PORT: '5432'
  TYPEORM_SYNCHRONIZE: 'false'
kind: ConfigMap
metadata:
  name: graphql-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  labels:
    app: backend
    backend: graphql
spec:
  selector:
    matchLabels:
      backend: graphql
  template:
    metadata:
      labels:
        app: backend
        backend: graphql
    spec:
      containers:
        - name: graphql
          image: adrfoong/sheep-backend
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: graphql-config
          env:
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: NODE_ENV
              value: production
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
