apiVersion: v1
data:
  POSTGRES_DB: baab
kind: ConfigMap
metadata:
  name: postgres-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: backend
    backend: postgres
spec:
  selector:
    matchLabels:
      backend: postgres
  template:
    metadata:
      labels:
        app: backend
        backend: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
