apiVersion: v1
kind: Service
metadata:
  name: baab
spec:
  type: LoadBalancer
  selector:
    app: baab
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: graphql
      port: 4000
      targetPort: 4000
